# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# proto-file: generator/generator_config.proto
# proto-message: GeneratorConfiguration

# Access Approval
service {
  service_proto_path: "google/cloud/accessapproval/v1/accessapproval.proto"
  product_path: "google/cloud/accessapproval"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Access Context Manager
service {
  service_proto_path: "google/identity/accesscontextmanager/v1/access_context_manager.proto"
  product_path: "google/cloud/accesscontextmanager"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# API Gateway
service {
  service_proto_path: "google/cloud/apigateway/v1/apigateway_service.proto"
  product_path: "google/cloud/apigateway"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable", "kUnknown"]
}

# Apigee Connect
service {
  service_proto_path: "google/cloud/apigeeconnect/v1/connection.proto"
  product_path: "google/cloud/apigeeconnect"
  initial_copyright_year: "2022"
  service_endpoint_env_var: "GOOGLE_CLOUD_CPP_APIGEE_CONNECTION_SERVICE_ENDPOINT"
  retryable_status_codes: ["kUnavailable", "kUnknown"]
}

# App Engine Admin
service {
  service_proto_path: "google/appengine/v1/appengine.proto"
  additional_proto_files: ["google/appengine/v1/operation.proto"]
  product_path: "google/cloud/appengine"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Artifact Registry
service {
  service_proto_path: "google/devtools/artifactregistry/v1/service.proto"
  product_path: "google/cloud/artifactregistry"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Cloud Asset
service {
  service_proto_path: "google/cloud/asset/v1/asset_service.proto"
  product_path: "google/cloud/asset"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Assured Workloads
service {
  service_proto_path: "google/cloud/assuredworkloads/v1/assuredworkloads.proto"
  product_path: "google/cloud/assuredworkloads"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Auto ML
service {
  service_proto_path: "google/cloud/automl/v1/service.proto"
  additional_proto_files: ["google/cloud/automl/v1/operations.proto"]
  product_path: "google/cloud/automl"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/automl/v1/prediction_service.proto"
  product_path: "google/cloud/automl"
  initial_copyright_year: "2022"
  service_endpoint_env_var: "GOOGLE_CLOUD_CPP_AUTOML_PREDICTION_SERVICE_ENDPOINT"
  retryable_status_codes: ["kUnavailable"]
}

# BigQuery
service {
  service_proto_path: "google/cloud/bigquery/storage/v1/storage.proto"
  product_path: "google/cloud/bigquery"
  initial_copyright_year: "2021"
  omitted_services: ["BigQueryWrite"]
  backwards_compatibility_namespace_alias: true
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/bigquery/storage/v1/storage.proto"
  product_path: "google/cloud/bigquery"
  initial_copyright_year: "2022"
  omitted_services: ["BigQueryRead"]
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/bigquery/connection/v1/connection.proto"
  product_path: "google/cloud/bigquery"
  initial_copyright_year: "2022"
  service_endpoint_env_var: "GOOGLE_CLOUD_CPP_BIGQUERY_CONNECTION_SERVICE_ENDPOINT"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/bigquery/reservation/v1/reservation.proto"
  product_path: "google/cloud/bigquery"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/bigquery/datatransfer/v1/datatransfer.proto"
  product_path: "google/cloud/bigquery"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/bigquery/v2/model.proto"
  product_path: "google/cloud/bigquery"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Bigtable
service {
  service_proto_path: "google/bigtable/admin/v2/bigtable_instance_admin.proto"
  product_path: "google/cloud/bigtable/admin"
  initial_copyright_year: "2021"
  emulator_endpoint_env_var: "BIGTABLE_INSTANCE_ADMIN_EMULATOR_HOST"
  retryable_status_codes: ["kUnavailable", "kAborted"]
}

service {
  service_proto_path: "google/bigtable/admin/v2/bigtable_table_admin.proto"
  product_path: "google/cloud/bigtable/admin"
  initial_copyright_year: "2021"
  omitted_rpcs: ["CreateTableFromSnapshot", "SnapshotTable", "GetSnapshot", "ListSnapshots", "DeleteSnapshot"]
  emulator_endpoint_env_var: "BIGTABLE_EMULATOR_HOST"
  gen_async_rpcs: ["CheckConsistency"]
  retryable_status_codes: ["kUnavailable", "kAborted"]
}

# Billing
service {
  service_proto_path: "google/cloud/billing/v1/cloud_billing.proto"
  product_path: "google/cloud/billing"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/billing/v1/cloud_catalog.proto"
  product_path: "google/cloud/billing"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/billing/budgets/v1/budget_service.proto"
  product_path: "google/cloud/billing"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Binary Authorization
service {
  service_proto_path: "google/cloud/binaryauthorization/v1/service.proto"
  product_path: "google/cloud/binaryauthorization"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Certificate Authority
service {
  service_proto_path: "google/cloud/security/privateca/v1/service.proto"
  product_path: "google/cloud/privateca"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable", "kUnknown"]
}

# Cloud Build
service {
  service_proto_path: "google/devtools/cloudbuild/v1/cloudbuild.proto"
  product_path: "google/cloud/cloudbuild"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Cloud Channel
service {
  service_proto_path: "google/cloud/channel/v1/service.proto"
  additional_proto_files: ["google/cloud/channel/v1/operations.proto"]
  product_path: "google/cloud/channel"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Cloud Debugger
service {
  service_proto_path: "google/devtools/clouddebugger/v2/controller.proto"
  product_path: "google/cloud/debugger"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/devtools/clouddebugger/v2/debugger.proto"
  product_path: "google/cloud/debugger"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Composer
service {
  service_proto_path: "google/cloud/orchestration/airflow/service/v1/environments.proto"
  additional_proto_files: ["google/cloud/orchestration/airflow/service/v1/operations.proto"]
  product_path: "google/cloud/composer"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/orchestration/airflow/service/v1/image_versions.proto"
  product_path: "google/cloud/composer"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Contact Center AI Insights
service {
  service_proto_path: "google/cloud/contactcenterinsights/v1/contact_center_insights.proto"
  product_path: "google/cloud/contactcenterinsights"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Container
service {
  service_proto_path: "google/container/v1/cluster_service.proto"
  product_path: "google/cloud/container"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Container Analysis
service {
  service_proto_path: "google/devtools/containeranalysis/v1/containeranalysis.proto"
  additional_proto_files: ["grafeas/v1/grafeas.proto"]
  product_path: "google/cloud/containeranalysis"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Data Catalog
service {
  service_proto_path: "google/cloud/datacatalog/v1/datacatalog.proto"
  product_path: "google/cloud/datacatalog"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/datacatalog/v1/policytagmanager.proto"
  product_path: "google/cloud/datacatalog"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/datacatalog/v1/policytagmanagerserialization.proto"
  product_path: "google/cloud/datacatalog"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Database Migration
service {
  service_proto_path: "google/cloud/clouddms/v1/clouddms.proto"
  product_path: "google/cloud/datamigration"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Dataproc
service {
  service_proto_path: "google/cloud/dataproc/v1/autoscaling_policies.proto"
  product_path: "google/cloud/dataproc"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/dataproc/v1/batches.proto"
  additional_proto_files: ["google/cloud/dataproc/v1/operations.proto"]
  product_path: "google/cloud/dataproc"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/dataproc/v1/clusters.proto"
  additional_proto_files: ["google/cloud/dataproc/v1/operations.proto"]
  product_path: "google/cloud/dataproc"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/dataproc/v1/jobs.proto"
  product_path: "google/cloud/dataproc"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/dataproc/v1/workflow_templates.proto"
  product_path: "google/cloud/dataproc"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Data Loss Prevention
service {
  service_proto_path: "google/privacy/dlp/v2/dlp.proto"
  product_path: "google/cloud/dlp"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Dialogflow CX
service {
  service_proto_path: "google/cloud/dialogflow/cx/v3/environment.proto"
  additional_proto_files: ["google/protobuf/struct.proto"]
  product_path: "google/cloud/dialogflow_cx"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/dialogflow/cx/v3/experiment.proto"
  product_path: "google/cloud/dialogflow_cx"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/dialogflow/cx/v3/session_entity_type.proto"
  product_path: "google/cloud/dialogflow_cx"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/dialogflow/cx/v3/version.proto"
  additional_proto_files: ["google/protobuf/struct.proto"]
  product_path: "google/cloud/dialogflow_cx"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/dialogflow/cx/v3/page.proto"
  product_path: "google/cloud/dialogflow_cx"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/dialogflow/cx/v3/session.proto"
  product_path: "google/cloud/dialogflow_cx"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/dialogflow/cx/v3/intent.proto"
  product_path: "google/cloud/dialogflow_cx"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/dialogflow/cx/v3/agent.proto"
  additional_proto_files: ["google/protobuf/struct.proto"]
  product_path: "google/cloud/dialogflow_cx"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/dialogflow/cx/v3/security_settings.proto"
  product_path: "google/cloud/dialogflow_cx"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/dialogflow/cx/v3/flow.proto"
  additional_proto_files: ["google/protobuf/struct.proto"]
  product_path: "google/cloud/dialogflow_cx"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/dialogflow/cx/v3/entity_type.proto"
  product_path: "google/cloud/dialogflow_cx"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/dialogflow/cx/v3/transition_route_group.proto"
  product_path: "google/cloud/dialogflow_cx"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/dialogflow/cx/v3/webhook.proto"
  product_path: "google/cloud/dialogflow_cx"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/dialogflow/cx/v3/changelog.proto"
  product_path: "google/cloud/dialogflow_cx"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/dialogflow/cx/v3/test_case.proto"
  product_path: "google/cloud/dialogflow_cx"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/dialogflow/cx/v3/deployment.proto"
  product_path: "google/cloud/dialogflow_cx"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Document AI
service {
  service_proto_path: "google/cloud/documentai/v1/document_processor_service.proto"
  product_path: "google/cloud/documentai"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Eventarc
service {
  service_proto_path: "google/cloud/eventarc/v1/eventarc.proto"
  product_path: "google/cloud/eventarc"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable", "kUnknown"]
}

service {
  service_proto_path: "google/cloud/eventarc/publishing/v1/publisher.proto"
  product_path: "google/cloud/eventarc"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Filestore
service {
  service_proto_path: "google/cloud/filestore/v1/cloud_filestore_service.proto"
  product_path: "google/cloud/filestore"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Functions
service {
  service_proto_path: "google/cloud/functions/v1/functions.proto"
  additional_proto_files: ["google/cloud/functions/v1/operations.proto"]
  product_path: "google/cloud/functions"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Game Services
service {
  service_proto_path: "google/cloud/gaming/v1/game_server_clusters_service.proto"
  product_path: "google/cloud/gameservices"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/gaming/v1/game_server_configs_service.proto"
  product_path: "google/cloud/gameservices"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/gaming/v1/game_server_deployments_service.proto"
  product_path: "google/cloud/gameservices"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/gaming/v1/realms_service.proto"
  product_path: "google/cloud/gameservices"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# GKE Hub
service {
  service_proto_path: "google/cloud/gkehub/v1/service.proto"
  product_path: "google/cloud/gkehub"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# IAM
service {
  service_proto_path: "google/iam/credentials/v1/iamcredentials.proto"
  product_path: "google/cloud/iam"
  initial_copyright_year: "2020"
  backwards_compatibility_namespace_alias: true
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/iam/admin/v1/iam.proto"
  product_path: "google/cloud/iam"
  initial_copyright_year: "2021"
  omitted_rpcs: ["SignBlob", "SignJwt", "UpdateServiceAccount"]
  backwards_compatibility_namespace_alias: true
  retryable_status_codes: ["kUnavailable"]
}

# Identity-Aware Proxy (IAP)
service {
  service_proto_path: "google/cloud/iap/v1/service.proto"
  product_path: "google/cloud/iap"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# IAM Policy Troubleshooter
service {
  service_proto_path: "google/cloud/policytroubleshooter/v1/checker.proto"
  product_path: "google/cloud/policytroubleshooter"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# IDS (Cloud Intrusion Detection System)
service {
  service_proto_path: "google/cloud/ids/v1/ids.proto"
  product_path: "google/cloud/ids"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# IoT (Internet of Things)
service {
  service_proto_path: "google/cloud/iot/v1/device_manager.proto"
  product_path: "google/cloud/iot"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# KMS
service {
  service_proto_path: "google/cloud/kms/v1/service.proto"
  product_path: "google/cloud/kms"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/kms/v1/ekm_service.proto"
  product_path: "google/cloud/kms"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Language
service {
  service_proto_path: "google/cloud/language/v1/language_service.proto"
  product_path: "google/cloud/language"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Logging
service {
  service_proto_path: "google/logging/v2/logging.proto"
  product_path: "google/cloud/logging"
  initial_copyright_year: "2021"
  retryable_status_codes: ["kInternal", "kUnavailable"]
}

# Managed Microsoft Active Directory (Managed Microsoft AD or Managed Identities)
service {
  service_proto_path: "google/cloud/managedidentities/v1/managed_identities_service.proto"
  product_path: "google/cloud/managedidentities"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Memcache
service {
  service_proto_path: "google/cloud/memcache/v1/cloud_memcache.proto"
  product_path: "google/cloud/memcache"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Monitoring
service {
  service_proto_path: "google/monitoring/v3/alert_service.proto"
  product_path: "google/cloud/monitoring"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/monitoring/v3/group_service.proto"
  product_path: "google/cloud/monitoring"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/monitoring/v3/metric_service.proto"
  product_path: "google/cloud/monitoring"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/monitoring/v3/notification_service.proto"
  product_path: "google/cloud/monitoring"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/monitoring/v3/query_service.proto"
  product_path: "google/cloud/monitoring"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/monitoring/v3/service_service.proto"
  product_path: "google/cloud/monitoring"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/monitoring/v3/uptime_service.proto"
  product_path: "google/cloud/monitoring"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/monitoring/dashboard/v1/dashboards_service.proto"
  product_path: "google/cloud/monitoring"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/monitoring/metricsscope/v1/metrics_scopes.proto"
  product_path: "google/cloud/monitoring"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Network Management
service {
  service_proto_path: "google/cloud/networkmanagement/v1/reachability.proto"
  product_path: "google/cloud/networkmanagement"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Notebooks
service {
  service_proto_path: "google/cloud/notebooks/v1/managed_service.proto"
  additional_proto_files: ["google/cloud/notebooks/v1/service.proto"]
  product_path: "google/cloud/notebooks"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Organization Policy
service {
  service_proto_path: "google/cloud/orgpolicy/v2/orgpolicy.proto"
  product_path: "google/cloud/orgpolicy"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# OS Config
service {
  service_proto_path: "google/cloud/osconfig/v1/osconfig_service.proto"
  product_path: "google/cloud/osconfig"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/osconfig/agentendpoint/v1/agentendpoint.proto"
  product_path: "google/cloud/osconfig"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# OS Login
service {
  service_proto_path: "google/cloud/oslogin/v1/oslogin.proto"
  product_path: "google/cloud/oslogin"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Cloud Profiler
service {
  service_proto_path: "google/devtools/cloudprofiler/v2/profiler.proto"
  product_path: "google/cloud/profiler"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Pub/Sub Lite
service {
  service_proto_path: "google/cloud/pubsublite/v1/admin.proto"
  product_path: "google/cloud/pubsublite"
  initial_copyright_year: "2021"
  gen_async_rpcs: ["GetTopicPartitions"]
  retryable_status_codes: ["kInternal", "kUnavailable"]
}

service {
  service_proto_path: "google/cloud/pubsublite/v1/cursor.proto"
  product_path: "google/cloud/pubsublite"
  initial_copyright_year: "2022"
  omit_client: true
  omit_connection: true
}

service {
  service_proto_path: "google/cloud/pubsublite/v1/publisher.proto"
  product_path: "google/cloud/pubsublite"
  initial_copyright_year: "2022"
  omit_client: true
  omit_connection: true
}

service {
  service_proto_path: "google/cloud/pubsublite/v1/subscriber.proto"
  product_path: "google/cloud/pubsublite"
  initial_copyright_year: "2022"
  omit_client: true
  omit_connection: true
}

service {
  service_proto_path: "google/cloud/pubsublite/v1/topic_stats.proto"
  product_path: "google/cloud/pubsublite"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kInternal", "kUnavailable"]
}

# Recommender
service {
  service_proto_path: "google/cloud/recommender/v1/recommender_service.proto"
  product_path: "google/cloud/recommender"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Redis
service {
  service_proto_path: "google/cloud/redis/v1/cloud_redis.proto"
  product_path: "google/cloud/redis"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Resource Manager
service {
  service_proto_path: "google/cloud/resourcemanager/v3/folders.proto"
  product_path: "google/cloud/resourcemanager"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/resourcemanager/v3/organizations.proto"
  product_path: "google/cloud/resourcemanager"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/resourcemanager/v3/projects.proto"
  product_path: "google/cloud/resourcemanager"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Resource Settings
service {
  service_proto_path: "google/cloud/resourcesettings/v1/resource_settings.proto"
  product_path: "google/cloud/resourcesettings"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Retail
service {
  service_proto_path: "google/cloud/retail/v2/catalog_service.proto"
  product_path: "google/cloud/retail"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/retail/v2/completion_service.proto"
  product_path: "google/cloud/retail"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/retail/v2/prediction_service.proto"
  product_path: "google/cloud/retail"
  initial_copyright_year: "2022"
  service_endpoint_env_var: "GOOGLE_CLOUD_CPP_RETAIL_PREDICTION_SERVICE_ENDPOINT"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/retail/v2/product_service.proto"
  product_path: "google/cloud/retail"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/retail/v2/search_service.proto"
  product_path: "google/cloud/retail"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/retail/v2/user_event_service.proto"
  product_path: "google/cloud/retail"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Scheduler
service {
  service_proto_path: "google/cloud/scheduler/v1/cloudscheduler.proto"
  product_path: "google/cloud/scheduler"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Secret Manager
service {
  service_proto_path: "google/cloud/secretmanager/v1/service.proto"
  product_path: "google/cloud/secretmanager"
  initial_copyright_year: "2021"
  retryable_status_codes: ["kUnavailable"]
}

# Security Center
service {
  service_proto_path: "google/cloud/securitycenter/v1/securitycenter_service.proto"
  product_path: "google/cloud/securitycenter"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Service Control
service {
  service_proto_path: "google/api/servicecontrol/v1/quota_controller.proto"
  product_path: "google/cloud/servicecontrol"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/api/servicecontrol/v1/service_controller.proto"
  product_path: "google/cloud/servicecontrol"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Service Directory
service {
  service_proto_path: "google/cloud/servicedirectory/v1/lookup_service.proto"
  product_path: "google/cloud/servicedirectory"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable", "kUnknown"]
}

service {
  service_proto_path: "google/cloud/servicedirectory/v1/registration_service.proto"
  product_path: "google/cloud/servicedirectory"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable", "kUnknown"]
}

# Service Management
service {
  service_proto_path: "google/api/servicemanagement/v1/servicemanager.proto"
  product_path: "google/cloud/servicemanagement"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Service Usage
service {
  service_proto_path: "google/api/serviceusage/v1/serviceusage.proto"
  product_path: "google/cloud/serviceusage"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Shell
service {
  service_proto_path: "google/cloud/shell/v1/cloudshell.proto"
  product_path: "google/cloud/shell"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable", "kUnknown"]
}

# Spanner
service {
  service_proto_path: "google/spanner/admin/database/v1/spanner_database_admin.proto"
  product_path: "google/cloud/spanner/admin"
  initial_copyright_year: "2021"
  service_endpoint_env_var: "GOOGLE_CLOUD_CPP_SPANNER_DEFAULT_ENDPOINT"
  emulator_endpoint_env_var: "SPANNER_EMULATOR_HOST"
  backwards_compatibility_namespace_alias: true
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/spanner/admin/instance/v1/spanner_instance_admin.proto"
  product_path: "google/cloud/spanner/admin"
  initial_copyright_year: "2021"
  service_endpoint_env_var: "GOOGLE_CLOUD_CPP_SPANNER_DEFAULT_ENDPOINT"
  emulator_endpoint_env_var: "SPANNER_EMULATOR_HOST"
  backwards_compatibility_namespace_alias: true
  retryable_status_codes: ["kUnavailable"]
}

# Speech
service {
  service_proto_path: "google/cloud/speech/v1/cloud_speech.proto"
  product_path: "google/cloud/speech"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Storage
service {
  service_proto_path: "google/storage/v2/storage.proto"
  product_path: "google/cloud/storage"
  initial_copyright_year: "2022"
  omit_client: true
  omit_connection: true
  omit_stub_factory: true
  omitted_rpcs: [
    "DeleteNotification",
    "GetNotification",
    "CreateNotification",
    "ListNotifications",
    "CreateHmacKey",
    "DeleteHmacKey",
    "GetHmacKey",
    "ListHmacKeys",
    "UpdateHmacKey"
  ]
}

# Storage Transfer Service
service {
  service_proto_path: "google/storagetransfer/v1/transfer.proto"
  product_path: "google/cloud/storagetransfer"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Talent
service {
  service_proto_path: "google/cloud/talent/v4/company_service.proto"
  product_path: "google/cloud/talent"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/talent/v4/completion_service.proto"
  product_path: "google/cloud/talent"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/talent/v4/event_service.proto"
  product_path: "google/cloud/talent"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/talent/v4/job_service.proto"
  product_path: "google/cloud/talent"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/talent/v4/tenant_service.proto"
  product_path: "google/cloud/talent"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Tasks
service {
  service_proto_path: "google/cloud/tasks/v2/cloudtasks.proto"
  product_path: "google/cloud/tasks"
  initial_copyright_year: "2021"
  retryable_status_codes: ["kInternal", "kUnavailable"]
}

# Text-to-Speech
service {
  service_proto_path: "google/cloud/texttospeech/v1/cloud_tts.proto"
  product_path: "google/cloud/texttospeech"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# TPU
service {
  service_proto_path: "google/cloud/tpu/v1/cloud_tpu.proto"
  product_path: "google/cloud/tpu"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Cloud Trace
service {
  service_proto_path: "google/devtools/cloudtrace/v2/tracing.proto"
  product_path: "google/cloud/trace"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Translate
service {
  service_proto_path: "google/cloud/translate/v3/translation_service.proto"
  product_path: "google/cloud/translate"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Video Intelligence
service {
  service_proto_path: "google/cloud/videointelligence/v1/video_intelligence.proto"
  product_path: "google/cloud/videointelligence"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Vision
service {
  service_proto_path: "google/cloud/vision/v1/image_annotator.proto"
  product_path: "google/cloud/vision"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/vision/v1/product_search_service.proto"
  product_path: "google/cloud/vision"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# VM Migration
service {
  service_proto_path: "google/cloud/vmmigration/v1/vmmigration.proto"
  product_path: "google/cloud/vmmigration"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Serverless VPC Access
service {
  service_proto_path: "google/cloud/vpcaccess/v1/vpc_access.proto"
  product_path: "google/cloud/vpcaccess"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable", "kUnknown"]
}

# Web Risk
service {
  service_proto_path: "google/cloud/webrisk/v1/webrisk.proto"
  product_path: "google/cloud/webrisk"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Web Security Scanner
service {
  service_proto_path: "google/cloud/websecurityscanner/v1/web_security_scanner.proto"
  product_path: "google/cloud/websecurityscanner"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

# Workflows
service {
  service_proto_path: "google/cloud/workflows/v1/workflows.proto"
  product_path: "google/cloud/workflows"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}

service {
  service_proto_path: "google/cloud/workflows/executions/v1/executions.proto"
  product_path: "google/cloud/workflows"
  initial_copyright_year: "2022"
  retryable_status_codes: ["kUnavailable"]
}
