# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG DISTRO_VERSION=stretch
FROM debian:${DISTRO_VERSION}
MAINTAINER "Carlos O'Ryan <coryan@google.com>"

# Please keep the formatting in these commands, it is optimized to cut & paste
# into the README.md file.
RUN apt update
RUN apt install -y build-essential cmake git gcc g++ cmake libcurl4-openssl-dev libssl-dev make zlib1g-dev

ARG CXX=g++
ARG CC=gcc

WORKDIR /var/tmp/
RUN git clone https://github.com/GoogleCloudPlatform/google-cloud-cpp.git
WORKDIR /var/tmp/google-cloud-cpp
RUN git submodule update --init
RUN cmake -H. -Bbuild-output
RUN cmake --build build-output -- -j $(nproc)
WORKDIR /var/tmp/google-cloud-cpp/build-output
RUN ctest --output-on-failure
