# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG DISTRO_VERSION=trusty
FROM ubuntu:${DISTRO_VERSION}
MAINTAINER "Carlos O'Ryan <coryan@google.com>"

# Please keep the formatting in these commands, it is optimized to cut & paste
# into the README.md file.
RUN apt update
RUN apt install -y software-properties-common
RUN add-apt-repository ppa:ubuntu-toolchain-r/test -y
RUN apt update
RUN apt install -y cmake3 git gcc-4.9 g++-4.9 make wget zlib1g-dev
RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 100
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 100
WORKDIR /var/tmp/
RUN wget -q https://www.openssl.org/source/openssl-1.0.2n.tar.gz
RUN tar xf openssl-1.0.2n.tar.gz
WORKDIR /var/tmp/openssl-1.0.2n
RUN ./Configure --prefix=/usr/local --openssldir=/usr/local linux-x86_64 shared
RUN make -j $(nproc)
RUN make install

#RUN export CMAKE_FLAGS=-DOPENSSL_ROOT_DIR=/usr/local
WORKDIR /var/tmp/
RUN wget -q https://curl.haxx.se/download/curl-7.61.0.tar.gz
RUN tar xf curl-7.61.0.tar.gz
WORKDIR /var/tmp/curl-7.61.0
RUN ./configure
RUN make -j $(nproc)
RUN make install

ARG CXX=g++
ARG CC=gcc

WORKDIR /var/tmp/
RUN git clone https://github.com/GoogleCloudPlatform/google-cloud-cpp.git
WORKDIR /var/tmp/google-cloud-cpp
RUN git submodule update --init
RUN cmake -H. -Bbuild-output
RUN cmake --build build-output -- -j $(nproc)
WORKDIR /var/tmp/google-cloud-cpp/build-output
RUN ctest --output-on-failure
