var searchData=
[
  ['client_635',['Client',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1Client.html',1,'google::cloud::spanner::v1::Client'],['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1Client.html',1,'google::cloud::spanner::v1::Client']]],
  ['clientoptions_636',['ClientOptions',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1ClientOptions.html',1,'google::cloud::spanner::v1::ClientOptions'],['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1ClientOptions.html',1,'google::cloud::spanner::v1::ClientOptions']]],
  ['commitoptions_637',['CommitOptions',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1CommitOptions.html',1,'google::cloud::spanner::v1::CommitOptions'],['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1CommitOptions.html',1,'google::cloud::spanner::v1::CommitOptions']]],
  ['commitparams_638',['CommitParams',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1Connection_1_1CommitParams.html',1,'google::cloud::spanner::v1::Connection']]],
  ['commitresult_639',['CommitResult',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1CommitResult.html',1,'google::cloud::spanner::v1::CommitResult'],['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1CommitResult.html',1,'google::cloud::spanner::v1::CommitResult']]],
  ['commitstats_640',['CommitStats',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1CommitStats.html',1,'google::cloud::spanner::v1::CommitStats'],['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1CommitStats.html',1,'google::cloud::spanner::v1::CommitStats']]],
  ['committimestamp_641',['CommitTimestamp',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1CommitTimestamp.html',1,'google::cloud::spanner::v1::CommitTimestamp'],['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1CommitTimestamp.html',1,'google::cloud::spanner::v1::CommitTimestamp']]],
  ['completionqueue_642',['CompletionQueue',['https://googleapis.dev/cpp/google-cloud-common/latest/classgoogle_1_1cloud_1_1v1_1_1CompletionQueue.html',1,'google::cloud::v1']]],
  ['connection_643',['Connection',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1Connection.html',1,'google::cloud::spanner::v1::Connection'],['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1Connection.html',1,'google::cloud::spanner::v1::Connection']]],
  ['connectionoptions_644',['ConnectionOptions',['https://googleapis.dev/cpp/google-cloud-common/latest/classgoogle_1_1cloud_1_1v1_1_1ConnectionOptions.html',1,'google::cloud::v1']]],
  ['connectionoptionstraits_645',['ConnectionOptionsTraits',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1ConnectionOptionsTraits.html',1,'google::cloud::spanner::v1::ConnectionOptionsTraits'],['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1ConnectionOptionsTraits.html',1,'google::cloud::spanner::v1::ConnectionOptionsTraits']]],
  ['createbackupparams_646',['CreateBackupParams',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1DatabaseAdminConnection_1_1CreateBackupParams.html',1,'google::cloud::spanner::v1::DatabaseAdminConnection']]],
  ['createdatabaseparams_647',['CreateDatabaseParams',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1DatabaseAdminConnection_1_1CreateDatabaseParams.html',1,'google::cloud::spanner::v1::DatabaseAdminConnection']]],
  ['createinstanceparams_648',['CreateInstanceParams',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1InstanceAdminConnection_1_1CreateInstanceParams.html',1,'google::cloud::spanner::v1::InstanceAdminConnection']]],
  ['createinstancerequestbuilder_649',['CreateInstanceRequestBuilder',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1CreateInstanceRequestBuilder.html',1,'google::cloud::spanner::v1::CreateInstanceRequestBuilder'],['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1CreateInstanceRequestBuilder.html',1,'google::cloud::spanner::v1::CreateInstanceRequestBuilder']]]
];
