var searchData=
[
  ['client_630',['Client',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1Client.html',1,'google::cloud::spanner::v1::Client'],['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1Client.html',1,'google::cloud::spanner::v1::Client']]],
  ['clientoptions_631',['ClientOptions',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1ClientOptions.html',1,'google::cloud::spanner::v1::ClientOptions'],['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1ClientOptions.html',1,'google::cloud::spanner::v1::ClientOptions']]],
  ['commitoptions_632',['CommitOptions',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1CommitOptions.html',1,'google::cloud::spanner::v1::CommitOptions'],['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1CommitOptions.html',1,'google::cloud::spanner::v1::CommitOptions']]],
  ['commitparams_633',['CommitParams',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1Connection_1_1CommitParams.html',1,'google::cloud::spanner::v1::Connection']]],
  ['commitresult_634',['CommitResult',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1CommitResult.html',1,'google::cloud::spanner::v1::CommitResult'],['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1CommitResult.html',1,'google::cloud::spanner::v1::CommitResult']]],
  ['commitstats_635',['CommitStats',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1CommitStats.html',1,'google::cloud::spanner::v1::CommitStats'],['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1CommitStats.html',1,'google::cloud::spanner::v1::CommitStats']]],
  ['committimestamp_636',['CommitTimestamp',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1CommitTimestamp.html',1,'google::cloud::spanner::v1::CommitTimestamp'],['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1CommitTimestamp.html',1,'google::cloud::spanner::v1::CommitTimestamp']]],
  ['completionqueue_637',['CompletionQueue',['https://googleapis.dev/cpp/google-cloud-common/latest/classgoogle_1_1cloud_1_1v1_1_1CompletionQueue.html',1,'google::cloud::v1']]],
  ['connection_638',['Connection',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1Connection.html',1,'google::cloud::spanner::v1::Connection'],['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1Connection.html',1,'google::cloud::spanner::v1::Connection']]],
  ['connectionoptions_639',['ConnectionOptions',['https://googleapis.dev/cpp/google-cloud-common/latest/classgoogle_1_1cloud_1_1v1_1_1ConnectionOptions.html',1,'google::cloud::v1']]],
  ['connectionoptionstraits_640',['ConnectionOptionsTraits',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1ConnectionOptionsTraits.html',1,'google::cloud::spanner::v1::ConnectionOptionsTraits'],['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1ConnectionOptionsTraits.html',1,'google::cloud::spanner::v1::ConnectionOptionsTraits']]],
  ['createbackupparams_641',['CreateBackupParams',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1DatabaseAdminConnection_1_1CreateBackupParams.html',1,'google::cloud::spanner::v1::DatabaseAdminConnection']]],
  ['createdatabaseparams_642',['CreateDatabaseParams',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1DatabaseAdminConnection_1_1CreateDatabaseParams.html',1,'google::cloud::spanner::v1::DatabaseAdminConnection']]],
  ['createinstanceparams_643',['CreateInstanceParams',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1InstanceAdminConnection_1_1CreateInstanceParams.html',1,'google::cloud::spanner::v1::InstanceAdminConnection']]],
  ['createinstancerequestbuilder_644',['CreateInstanceRequestBuilder',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1CreateInstanceRequestBuilder.html',1,'google::cloud::spanner::v1::CreateInstanceRequestBuilder'],['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1CreateInstanceRequestBuilder.html',1,'google::cloud::spanner::v1::CreateInstanceRequestBuilder']]]
];
