var searchData=
[
  ['readonlyoptions_773',['ReadOnlyOptions',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1Transaction_1_1ReadOnlyOptions.html',1,'google::cloud::spanner::v1::Transaction']]],
  ['readoptions_774',['ReadOptions',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1ReadOptions.html',1,'google::cloud::spanner::v1::ReadOptions'],['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1ReadOptions.html',1,'google::cloud::spanner::v1::ReadOptions']]],
  ['readparams_775',['ReadParams',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1Connection_1_1ReadParams.html',1,'google::cloud::spanner::v1::Connection']]],
  ['readpartition_776',['ReadPartition',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1ReadPartition.html',1,'google::cloud::spanner::v1::ReadPartition'],['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1ReadPartition.html',1,'google::cloud::spanner::v1::ReadPartition']]],
  ['readpartitioninternals_777',['ReadPartitionInternals',['../structgoogle_1_1cloud_1_1spanner__internal_1_1v1_1_1ReadPartitionInternals.html',1,'google::cloud::spanner_internal::v1::ReadPartitionInternals'],['../structgoogle_1_1cloud_1_1spanner__internal_1_1v1_1_1ReadPartitionInternals.html',1,'google::cloud::spanner_internal::v1::ReadPartitionInternals']]],
  ['readwriteoptions_778',['ReadWriteOptions',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1Transaction_1_1ReadWriteOptions.html',1,'google::cloud::spanner::v1::Transaction']]],
  ['replaceop_779',['ReplaceOp',['../structgoogle_1_1cloud_1_1spanner__internal_1_1v1_1_1ReplaceOp.html',1,'google::cloud::spanner_internal::v1::ReplaceOp'],['../structgoogle_1_1cloud_1_1spanner__internal_1_1v1_1_1ReplaceOp.html',1,'google::cloud::spanner_internal::v1::ReplaceOp']]],
  ['requestpriorityoption_780',['RequestPriorityOption',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1RequestPriorityOption.html',1,'google::cloud::spanner::v1::RequestPriorityOption'],['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1RequestPriorityOption.html',1,'google::cloud::spanner::v1::RequestPriorityOption']]],
  ['restoredatabaseparams_781',['RestoreDatabaseParams',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1DatabaseAdminConnection_1_1RestoreDatabaseParams.html',1,'google::cloud::spanner::v1::DatabaseAdminConnection']]],
  ['resultsourceinterface_782',['ResultSourceInterface',['../classgoogle_1_1cloud_1_1spanner__internal_1_1v1_1_1ResultSourceInterface.html',1,'google::cloud::spanner_internal::v1::ResultSourceInterface'],['../classgoogle_1_1cloud_1_1spanner__internal_1_1v1_1_1ResultSourceInterface.html',1,'google::cloud::spanner_internal::v1::ResultSourceInterface']]],
  ['rollbackparams_783',['RollbackParams',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1Connection_1_1RollbackParams.html',1,'google::cloud::spanner::v1::Connection']]],
  ['row_784',['Row',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1Row.html',1,'google::cloud::spanner::v1::Row'],['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1Row.html',1,'google::cloud::spanner::v1::Row']]],
  ['rowstream_785',['RowStream',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1RowStream.html',1,'google::cloud::spanner::v1::RowStream'],['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1RowStream.html',1,'google::cloud::spanner::v1::RowStream']]],
  ['rowstreamiterator_786',['RowStreamIterator',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1RowStreamIterator.html',1,'google::cloud::spanner::v1::RowStreamIterator'],['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1RowStreamIterator.html',1,'google::cloud::spanner::v1::RowStreamIterator']]],
  ['runtimestatuserror_787',['RuntimeStatusError',['https://googleapis.dev/cpp/google-cloud-common/latest/classgoogle_1_1cloud_1_1v1_1_1RuntimeStatusError.html',1,'google::cloud::v1']]]
];
