var searchData=
[
  ['testiampermissionsparams_744',['TestIamPermissionsParams',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1InstanceAdminConnection_1_1TestIamPermissionsParams.html',1,'google::cloud::spanner::v1::InstanceAdminConnection::TestIamPermissionsParams'],['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1DatabaseAdminConnection_1_1TestIamPermissionsParams.html',1,'google::cloud::spanner::v1::DatabaseAdminConnection::TestIamPermissionsParams']]],
  ['timestamp_745',['Timestamp',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1Timestamp.html',1,'google::cloud::spanner::v1::Timestamp'],['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1Timestamp.html',1,'google::cloud::spanner::v1::Timestamp']]],
  ['tracingoptions_746',['TracingOptions',['https://googleapis.dev/cpp/google-cloud-common/latest/classgoogle_1_1cloud_1_1v1_1_1TracingOptions.html',1,'google::cloud::v1']]],
  ['transaction_747',['Transaction',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1Transaction.html',1,'google::cloud::spanner::v1::Transaction'],['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1Transaction.html',1,'google::cloud::spanner::v1::Transaction']]],
  ['transactioninternals_748',['TransactionInternals',['../structgoogle_1_1cloud_1_1spanner__internal_1_1v1_1_1TransactionInternals.html',1,'google::cloud::spanner_internal::v1::TransactionInternals'],['../structgoogle_1_1cloud_1_1spanner__internal_1_1v1_1_1TransactionInternals.html',1,'google::cloud::spanner_internal::v1::TransactionInternals']]],
  ['tuplestream_749',['TupleStream',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1TupleStream.html',1,'google::cloud::spanner::v1::TupleStream&lt; Tuple &gt;'],['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1TupleStream.html',1,'google::cloud::spanner::v1::TupleStream&lt; Tuple &gt;']]],
  ['tuplestreamiterator_750',['TupleStreamIterator',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1TupleStreamIterator.html',1,'google::cloud::spanner::v1::TupleStreamIterator&lt; Tuple &gt;'],['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1TupleStreamIterator.html',1,'google::cloud::spanner::v1::TupleStreamIterator&lt; Tuple &gt;']]]
];
