var searchData=
[
  ['database_692',['Database',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1Database.html',1,'google::cloud::spanner::v1::Database'],['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1Database.html',1,'google::cloud::spanner::v1::Database']]],
  ['databaseadminclient_693',['DatabaseAdminClient',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1DatabaseAdminClient.html',1,'google::cloud::spanner::v1::DatabaseAdminClient'],['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1DatabaseAdminClient.html',1,'google::cloud::spanner::v1::DatabaseAdminClient']]],
  ['databaseadminconnection_694',['DatabaseAdminConnection',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1DatabaseAdminConnection.html',1,'google::cloud::spanner::v1::DatabaseAdminConnection'],['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1DatabaseAdminConnection.html',1,'google::cloud::spanner::v1::DatabaseAdminConnection']]],
  ['defaultencryption_695',['DefaultEncryption',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1DefaultEncryption.html',1,'google::cloud::spanner::v1::DefaultEncryption'],['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1DefaultEncryption.html',1,'google::cloud::spanner::v1::DefaultEncryption']]],
  ['deletebackupparams_696',['DeleteBackupParams',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1DatabaseAdminConnection_1_1DeleteBackupParams.html',1,'google::cloud::spanner::v1::DatabaseAdminConnection']]],
  ['deleteinstanceparams_697',['DeleteInstanceParams',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1InstanceAdminConnection_1_1DeleteInstanceParams.html',1,'google::cloud::spanner::v1::InstanceAdminConnection']]],
  ['deletemutationbuilder_698',['DeleteMutationBuilder',['../classgoogle_1_1cloud_1_1spanner__internal_1_1v1_1_1DeleteMutationBuilder.html',1,'google::cloud::spanner_internal::v1::DeleteMutationBuilder'],['../classgoogle_1_1cloud_1_1spanner__internal_1_1v1_1_1DeleteMutationBuilder.html',1,'google::cloud::spanner_internal::v1::DeleteMutationBuilder']]],
  ['dmlresult_699',['DmlResult',['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1DmlResult.html',1,'google::cloud::spanner::v1::DmlResult'],['../classgoogle_1_1cloud_1_1spanner_1_1v1_1_1DmlResult.html',1,'google::cloud::spanner::v1::DmlResult']]],
  ['dropdatabaseparams_700',['DropDatabaseParams',['../structgoogle_1_1cloud_1_1spanner_1_1v1_1_1DatabaseAdminConnection_1_1DropDatabaseParams.html',1,'google::cloud::spanner::v1::DatabaseAdminConnection']]]
];
