// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/dataplex/v1/service.proto

#include "google/cloud/dataplex/v1/internal/dataplex_option_defaults.h"
#include "google/cloud/dataplex/v1/dataplex_connection.h"
#include "google/cloud/dataplex/v1/dataplex_options.h"
#include "google/cloud/internal/populate_common_options.h"
#include "google/cloud/internal/populate_grpc_options.h"
#include <memory>
#include <utility>

namespace google {
namespace cloud {
namespace dataplex_v1_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

namespace {
auto constexpr kBackoffScaling = 2.0;
}  // namespace

Options DataplexServiceDefaultOptions(Options options) {
  options = internal::PopulateCommonOptions(
      std::move(options), "GOOGLE_CLOUD_CPP_DATAPLEX_SERVICE_ENDPOINT",
      "", "GOOGLE_CLOUD_CPP_DATAPLEX_SERVICE_AUTHORITY",
      "dataplex.googleapis.com");
  options = internal::PopulateGrpcOptions(std::move(options));
  if (!options.has<dataplex_v1::DataplexServiceRetryPolicyOption>()) {
    options.set<dataplex_v1::DataplexServiceRetryPolicyOption>(
        dataplex_v1::DataplexServiceLimitedTimeRetryPolicy(
            std::chrono::minutes(30)).clone());
  }
  if (!options.has<dataplex_v1::DataplexServiceBackoffPolicyOption>()) {
    options.set<dataplex_v1::DataplexServiceBackoffPolicyOption>(
        ExponentialBackoffPolicy(std::chrono::seconds(0), std::chrono::seconds(1),
            std::chrono::minutes(5), kBackoffScaling, kBackoffScaling).clone());
  }
  if (!options.has<dataplex_v1::DataplexServicePollingPolicyOption>()) {
    options.set<dataplex_v1::DataplexServicePollingPolicyOption>(
        GenericPollingPolicy<
            dataplex_v1::DataplexServiceRetryPolicyOption::Type,
            dataplex_v1::DataplexServiceBackoffPolicyOption::Type>(
            options.get<dataplex_v1::DataplexServiceRetryPolicyOption>()->clone(),
            ExponentialBackoffPolicy(std::chrono::seconds(1),
            std::chrono::minutes(5), kBackoffScaling).clone()).clone());
  }
  if (!options.has<dataplex_v1::DataplexServiceConnectionIdempotencyPolicyOption>()) {
    options.set<dataplex_v1::DataplexServiceConnectionIdempotencyPolicyOption>(
        dataplex_v1::MakeDefaultDataplexServiceConnectionIdempotencyPolicy());
  }

  return options;
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace dataplex_v1_internal
}  // namespace cloud
}  // namespace google
