# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""This WORKSPACE shows how to use google-cloud-cpp-spanner from a larger Bazel project."""

workspace(name = "google_cloud_cpp_spanner_quickstart")

# Add the necessary Starlark functions to fetch google-cloud-cpp-spanner.
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Fetch the Cloud Spanner C++ library.
# NOTE: Update this version and SHA256 as needed.
http_archive(
    name = "com_github_googleapis_google_cloud_cpp_spanner",
    sha256 = "841d8d675d0bb51717bfc42c42d679617b6542358a01c007df6b897fec208060",
    strip_prefix = "google-cloud-cpp-spanner-1.2.0",
    url = "https://github.com/googleapis/google-cloud-cpp-spanner/archive/v1.2.0.tar.gz",
)

# Call a function to load the Cloud Spanner C++ library's direct dependencies.
load("@com_github_googleapis_google_cloud_cpp_spanner//bazel:google_cloud_cpp_spanner_deps.bzl", "google_cloud_cpp_spanner_deps")

google_cloud_cpp_spanner_deps()

# (optional) Only generate C++ from the protos.
load("@com_google_googleapis//:repository_rules.bzl", "switched_rules_by_language")

switched_rules_by_language(
    name = "com_google_googleapis_imports",
    cc = True,
    grpc = True,
)

# Load indirect dependencies due to
#     https://github.com/bazelbuild/bazel/issues/1943
load("@com_github_googleapis_google_cloud_cpp_common//bazel:google_cloud_cpp_common_deps.bzl", "google_cloud_cpp_common_deps")

google_cloud_cpp_common_deps()

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")

grpc_extra_deps()
