# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# proto-file: simple_up_200_down_100.textproto
# proto-message: Strategy

base: "price::close_price"
sample: "price::open_price"
conditions {
  threshold: 0.02
  moneyin: 200
}
conditions {
  threshold: -0.03
  moneyin: 100
}
