# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This WORKSPACE verifies that the google-cloud-cpp libraries can be loaded
# into a different Bazel project.
workspace(name="com_github_googleapis_google_cloud_cpp_test_install")

# Applications should use (maybe with a different version):
#
# http_archive(
#     name = "com_github_googleapis_google_cloud_cpp",
#     url = "http://github.com/googleapis/google-cloud-cpp/archive/v0.2.0.tar.gz",
#     sha256 = "5fa6577828e5f949178b13ed0411dd634527c9d2d8f00e433edbd6ef9e42a281",
# )
#
# But we want to test that the *current* version is correct.
local_repository(
    name="com_github_googleapis_google_cloud_cpp",
    path="../..",
)

load("@com_github_googleapis_google_cloud_cpp//bazel:google_cloud_cpp_deps.bzl", "google_cloud_cpp_deps")
google_cloud_cpp_deps()
# Have to manually call the corresponding function for gRPC:
#   https://github.com/bazelbuild/bazel/issues/1550
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
