# DO NOT EDIT -- GENERATED CODE
storage_client_unit_tests = [
    "bucket_metadata_test.cc",
    "bucket_test.cc",
    "internal/authorized_user_credentials_test.cc",
    "internal/binary_data_as_debug_string_test.cc",
    "internal/default_client_test.cc",
    "internal/get_bucket_metadata_request_test.cc",
    "internal/google_application_default_credentials_file_test.cc",
    "internal/insert_object_media_request_test.cc",
    "internal/list_objects_request_test.cc",
    "internal/logging_client_test.cc",
    "internal/metadata_parser_test.cc",
    "internal/nljson_test.cc",
    "internal/parse_rfc3339_test.cc",
    "internal/retry_client_test.cc",
    "internal/read_object_range_request_test.cc",
    "internal/service_account_credentials_test.cc",
    "list_objects_reader_test.cc",
    "object_metadata_test.cc",
    "object_stream_test.cc",
    "retry_policy_test.cc",
    "storage_client_options_test.cc",
    "link_test.cc",
]

