# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

cc_binary(
    name = "bigtable_hello_world",
    srcs = ["bigtable_hello_world.cc"],
    deps = ["//google/cloud/bigtable:bigtable_client"],
)

cc_binary(
    name = "bigtable_hello_app_profile",
    srcs = ["bigtable_hello_app_profile.cc"],
    deps = ["//google/cloud/bigtable:bigtable_client"],
)

cc_binary(
    name = "bigtable_quickstart",
    srcs = ["bigtable_quickstart.cc"],
    deps = ["//google/cloud/bigtable:bigtable_client"],
)

cc_binary(
    name = "bigtable_samples",
    srcs = ["bigtable_samples.cc"],
    deps = ["//google/cloud/bigtable:bigtable_client"],
)

cc_binary(
    name = "bigtable_instance_admin_snippets",
    srcs = ["bigtable_instance_admin_snippets.cc"],
    deps = ["//google/cloud/bigtable:bigtable_client"],
)

cc_binary(
    name = "bigtable_samples_instance_admin",
    srcs = ["bigtable_samples_instance_admin.cc"],
    deps = ["//google/cloud/bigtable:bigtable_client"],
)

cc_binary(
    name = "instance_admin_async_snippets",
    srcs = ["instance_admin_async_snippets.cc"],
    deps = ["//google/cloud/bigtable:bigtable_client"],
)

cc_binary(
    name = "table_admin_snippets",
    srcs = ["table_admin_snippets.cc"],
    deps = ["//google/cloud/bigtable:bigtable_client"],
)

cc_binary(
    name = "table_admin_async_snippets",
    srcs = ["table_admin_async_snippets.cc"],
    deps = ["//google/cloud/bigtable:bigtable_client"],
)

cc_binary(
    name = "data_snippets",
    srcs = ["data_snippets.cc"],
    deps = ["//google/cloud/bigtable:bigtable_client"],
)

cc_binary(
    name = "data_async_snippets",
    srcs = ["data_async_snippets.cc"],
    deps = ["//google/cloud/bigtable:bigtable_client"],
)
