# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# proto-file: generator/generator_config.proto
# proto-message: GeneratorConfiguration

service {
  service_proto_path: "generator/integration_tests/test.proto"
  additional_proto_files: "generator/integration_tests/backup.proto"
  product_path: "generator/integration_tests/golden/v1"
  initial_copyright_year: "2022"
  omitted_rpcs: ["Omitted1", "GoldenKitchenSink.Omitted2"]
  service_endpoint_env_var: "GOLDEN_KITCHEN_SINK_ENDPOINT"
  emulator_endpoint_env_var: "GOLDEN_KITCHEN_SINK_EMULATOR_HOST"
  gen_async_rpcs: ["GetDatabase", "DropDatabase", "StreamingRead", "StreamingWrite"]
  retryable_status_codes: ["GoldenKitchenSink.kInternal", "kUnavailable", "GoldenThingAdmin.kDeadlineExceeded"]
  generate_round_robin_decorator: true
  generate_rest_transport: true
}
