// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/devtools/containeranalysis/v1/containeranalysis.proto

#include "google/cloud/containeranalysis/v1/internal/container_analysis_stub_factory.h"
#include "google/cloud/common_options.h"
#include "google/cloud/containeranalysis/v1/internal/container_analysis_auth_decorator.h"
#include "google/cloud/containeranalysis/v1/internal/container_analysis_logging_decorator.h"
#include "google/cloud/containeranalysis/v1/internal/container_analysis_metadata_decorator.h"
#include "google/cloud/containeranalysis/v1/internal/container_analysis_stub.h"
#include "google/cloud/containeranalysis/v1/internal/container_analysis_tracing_stub.h"
#include "google/cloud/grpc_options.h"
#include "google/cloud/internal/algorithm.h"
#include "google/cloud/internal/opentelemetry.h"
#include "google/cloud/log.h"
#include "google/cloud/options.h"
#include <google/devtools/containeranalysis/v1/containeranalysis.grpc.pb.h>
#include <memory>
#include <utility>

namespace google {
namespace cloud {
namespace containeranalysis_v1_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

std::shared_ptr<ContainerAnalysisStub>
CreateDefaultContainerAnalysisStub(
    std::shared_ptr<internal::GrpcAuthenticationStrategy> auth,
    Options const& options) {
  auto channel = auth->CreateChannel(
    options.get<EndpointOption>(), internal::MakeChannelArguments(options));
  auto service_grpc_stub = google::devtools::containeranalysis::v1::ContainerAnalysis::NewStub(channel);
  std::shared_ptr<ContainerAnalysisStub> stub =
    std::make_shared<DefaultContainerAnalysisStub>(std::move(service_grpc_stub));

  if (auth->RequiresConfigureContext()) {
    stub = std::make_shared<ContainerAnalysisAuth>(
        std::move(auth), std::move(stub));
  }
  stub = std::make_shared<ContainerAnalysisMetadata>(
      std::move(stub), std::multimap<std::string, std::string>{});
  if (internal::Contains(
      options.get<LoggingComponentsOption>(), "rpc")) {
    GCP_LOG(INFO) << "Enabled logging for gRPC calls";
    stub = std::make_shared<ContainerAnalysisLogging>(
        std::move(stub),
        options.get<GrpcTracingOptionsOption>(),
        options.get<LoggingComponentsOption>());
  }
  if (internal::TracingEnabled(options)) {
    stub = MakeContainerAnalysisTracingStub(std::move(stub));
  }
  return stub;
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace containeranalysis_v1_internal
}  // namespace cloud
}  // namespace google
