#!/bin/bash
#
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Assume the CMakeCache remains valid between runs.
ALWAYS_RESET_CMAKE_CACHE=NO

# By default compile most features.
ENABLED_FEATURES=__ga_libraries__,__experimental_libraries__,opentelemetry

# By default compile only the storage library.
BAZEL_TARGETS=("//google/cloud/storage/...")

# Set to `YES` to run the unit tests.
RUN_UNIT_TESTS=YES

# Set to `YES` to run the clang-tidy fixes.
RUN_CLANG_TIDY_FIX=YES

# Set to the list of integration tests to run.
RUN_INTEGRATION_TESTS=YES
